---
sidebar: sidebar 
permalink: use/cache-manage.html 
keywords: volume caching, Volume caching 
summary: ボリューム キャッシュは、リモートの場所に永続的な書き込み可能なボリュームを提供します。ボリューム キャッシュを使用すると、データへのアクセスを高速化したり、頻繁にアクセスされるボリュームのトラフィックを軽減したりできます。キャッシュ ボリュームは、特にクライアントが同じデータに繰り返しアクセスする必要がある場合など、読み取り集中型のワークロードに最適です。 
---
= キャッシュを管理する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
キャッシュを編集したり、エクスポート ポリシーを変更したり、キャッシュのサイズを変更したり、キャッシュを削除したりできます。

ボリューム キャッシュを使用すると、次の目標を達成できます。

* キャッシュの詳細を表示します。
* キャッシュに別のエクスポート ポリシーを割り当てます。
* ボリューム キャッシュを編集し、サイズなどを変更します。編集には他のプロパティを表示および変更するオプションがあり、今後のリリースでは編集にさらに多くのプロパティが追加される予定です。
* 元のボリューム サイズのパーセンテージに基づいて既存のキャッシュのサイズを変更します。
* キャッシュを削除します。




== キャッシュの詳細を表示

キャッシュごとに、元のボリューム、作業環境、キャッシュ ボリュームなどを確認できます。

.手順
. NetApp Consoleの左側のナビゲーションから、*モビリティ* > *ボリューム キャッシュ* を選択します。
+
宛先システムで作成されたキャッシュ ボリュームのリストを表示できます。キャッシュのリストにはキャッシュの詳細が表示されます。

. リストをフィルタリングするには、「*フィルタリング +*」オプションを選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. *詳細の表示と編集*を選択します。
. 詳細を確認します。




== キャッシュを編集する

キャッシュの名前、ボリューム サイズ、エクスポート ポリシーを変更できます。

.手順
. NetApp Consoleの左側のナビゲーションから、*モビリティ* > *ボリューム キャッシュ* を選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. *詳細の表示と編集*を選択します。
. [基本構成] タブで、必要に応じて、キャッシュ名とキャッシュ ボリューム サイズを変更します。
. 必要に応じて、[キャッシュ アクセス] タブを展開し、次の値を変更します。
+
.. マウント パス。
.. 既存のものとは異なる輸出政策。


. SMB/CIFS 共有の詳細またはエクスポート ポリシー ルールを変更するには、オプションをクリックしてNetApp System Manager にアクセスします。
. *保存*を選択します。




== 別のキャッシュエクスポートポリシーを割り当てる

キャッシュに異なるエクスポート ポリシーを割り当てることができます。

ソース エクスポート ポリシー ルールをターゲット クラスターに適用する必要があります。


TIP: 既存のエクスポート ポリシーをキャッシュに割り当てることができます。エクスポート ポリシー ルールを変更することはできません。エクスポート ポリシーを変更する必要がある場合は、 NetApp System Manager を使用できます。

.手順
. NetApp Consoleの左側のナビゲーションから、*モビリティ* > *ボリューム キャッシュ* を選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. *エクスポート ポリシーの変更*を選択します。
. キャッシュに割り当てるエクスポート ポリシーを選択します。
. *保存*を選択します。




== キャッシュのサイズを変更する

ソース ボリュームのパーセンテージに基づいて、キャッシュ ボリュームのサイズを変更できます。

.手順
. NetApp Consoleの左側のナビゲーションから、*モビリティ* > *ボリューム キャッシュ* を選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. *サイズ変更*を選択します。
. 元のボリューム サイズの新しいパーセンテージを入力します。
+
キャッシュ ボリュームのサイズは新しいパーセンテージに合わせて変更されます。

. *保存*を選択します。




== キャッシュを削除する

キャッシュが不要になった場合は削除できます。これにより、ボリューム キャッシュ関係が削除され、ターゲット ボリューム キャッシュが削除されます。

.手順
. NetApp Consoleの左側のナビゲーションから、*モビリティ* > *ボリューム キャッシュ* を選択します。
. 行を選択し、右側の*アクション…*オプションを選択します。
. *削除*を選択します。
. ボックスにチェックを入れてください。
. *削除*を選択します。

