---
sidebar: sidebar 
permalink: get-started/cache-intro.html 
keywords: how volume caching works, what is volume caching, bluexp 
summary: ボリューム キャッシュは、リモートの場所に永続的な書き込み可能なボリュームを提供します。ボリューム キャッシュを使用すると、データへのアクセスを高速化したり、頻繁にアクセスされるボリュームのトラフィックを軽減したりできます。キャッシュ ボリュームは、特にクライアントが同じデータに繰り返しアクセスする必要がある場合など、読み取り集中型のワークロードに最適です。 
---
= ボリュームキャッシュについて学ぶ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9 ソフトウェアの機能であるボリューム キャッシュは、ファイル配布を簡素化し、リソースをユーザーやコンピューティング リソースの場所に近づけることで WAN の遅延を短縮し、WAN 帯域幅のコストを削減するリモート キャッシュ機能です。ボリューム キャッシュは、リモートの場所に永続的な書き込み可能なボリュームを提供します。ボリューム キャッシュを使用すると、データへのアクセスを高速化したり、頻繁にアクセスされるボリュームのトラフィックを軽減したりできます。キャッシュ ボリュームは、特にクライアントが同じデータに繰り返しアクセスする必要がある場合など、読み取り集中型のワークロードに最適です。

ボリューム キャッシングを使用すると、作業環境として、具体的にはAmazon FSx for NetApp ONTAP、 Cloud Volumes ONTAP、オンプレミスのクラウドのキャッシング機能を利用できます。

ボリューム キャッシュにより、ブランチ オフィスから企業のデータセットへのアクセスも可能になります。クラスター内の複数のコントローラーから頻繁にアクセスする必要があるデータである「ホット データ」を提供することで、主要なアプリケーションに提供されるパフォーマンスを向上させることができます。さらに、世界中の複数の場所にいるユーザーのローカルにホット データをキャッシュすることで、集中管理されたデータセットへの同時アクセスを可能にし、ホット データへのアクセス時の応答時間を短縮して、ユーザーのコラボレーションを強化できます。



== NetApp Console

ボリューム キャッシュには、 NetApp Consoleからアクセスできます。

NetApp Consoleは、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとデータ サービスの集中管理を提供します。NetAppデータ サービスにアクセスして使用するには、コンソールが必要です。管理インターフェースとして、1 つのインターフェースから多数のストレージ リソースを管理できます。コンソール管理者は、企業内のすべてのシステムのストレージとサービスへのアクセスを制御できます。

NetApp Consoleの使用を開始するためにライセンスやサブスクリプションは必要ありません。ストレージ システムまたはNetAppデータ サービスへの接続を確保するためにクラウドにコンソール エージェントを展開する必要がある場合にのみ料金が発生します。ただし、コンソールからアクセスできる一部のNetAppデータ サービスは、ライセンスまたはサブスクリプションベースです。

詳細はこちら https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp Console"]。



== キャッシュとは何ですか?

キャッシュは、ホストとデータのソースの間に存在する一時的な保存場所です。キャッシュの目的は、ソース データの頻繁にアクセスされる部分を、ソースからデータを取得するよりも速くデータを提供できるような方法で保存することです。キャッシュは、データが複数回アクセスされ、複数のホストによって共有される読み取り集中型の環境で最も効果を発揮します。キャッシュ システムは、データ ソースを備えたシステムよりも高速です。これは、より高速なストレージ システムと、キャッシュ ストレージ スペースがホストに近いことによって実現されます。



== ボリュームキャッシュの利点

ボリューム キャッシュには次のような利点があります。

* ハイブリッドクラウドインフラストラクチャのパフォーマンスを高速化
* あるクラウド プロバイダーから別のクラウド プロバイダーにデータをキャッシュすることでクラウド サイロを排除します。
* 保管コストの削減
* 地理的な場所を越えてコラボレーション
* 変化するIT環境に迅速に適応する能力
* クラウドでホストされるオンデマンドまたはサブスクリプションベースのボリューム キャッシュ




== ボリュームキャッシュでできること

ボリューム キャッシュにより、いくつかのNetAppテクノロジーを最大限に活用して、次の目標を達成できます。

* あるクラウドプロバイダーから別のクラウドプロバイダーにデータをキャッシュする
* キャッシュエクスポートポリシーの表示と編集
* 既存のキャッシュのサイズを変更する
* キャッシュを削除する




== 料金

NetApp はボリューム キャッシュに対して料金を請求しませんが、適用されるデータの受信および送信料金についてはクラウド プロバイダーに確認する必要があります。



== ライセンス

ボリューム キャッシュには特別なONTAPライセンスは必要ありません。



== ボリュームキャッシュの仕組み

キャッシュ ボリュームは、ソース ボリュームによってバックアップされる、まばらにデータが配置されたボリュームです。キャッシュ ボリュームは、ソース ボリュームと同じクラスター上に配置することも、別のクラスター上に配置することもできます。

キャッシュ ボリュームは、すべてのデータがキャッシュ ボリューム内にあることを必要とせずに、ソース ボリュームのデータにアクセスできるようにします。キャッシュ ボリューム内のデータ ストレージは、ホット データ (作業データまたは最近使用されたデータ) のみを保持することによって効率的に管理されます。

ボリューム キャッシュは、クライアントが要求したデータがキャッシュ ボリュームに含まれている場合に要求を読み取ります。それ以外の場合、ボリューム キャッシュ サービスはソース ボリュームからデータを要求し、クライアント要求に応える前にデータを保存します。その後のデータ要求はキャッシュ ボリュームから直接提供されます。これにより、最初のリクエスト後は、データがネットワークを介して移動したり、過負荷のシステムから提供される必要がなくなるため、同じデータに繰り返しアクセスする場合のパフォーマンスが向上します。
