---
sidebar: sidebar 
permalink: release-notes/cache-limitations.html 
keywords: volume caching, bluexp 
summary: 既知の制限事項では、このリリースのサービスでサポートされていない、または正しく相互運用されないプラットフォーム、デバイス、または機能が特定されます。 
---
= ボリュームキャッシュの既知の制限
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既知の制限事項では、このリリースのサービスでサポートされていない、または正しく相互運用されないプラットフォーム、デバイス、または機能が特定されます。



== キャッシュエクスポートポリシールールのコピーに関する制限

次の状況では、キャッシュ エクスポート ポリシー ルールはキャッシュ ボリュームにコピーされません。

* ソースボリュームのシステムがAmazon FSx for NetApp ONTAPまたはCloud Volumes ONTAPであり、キャッシュボリュームがONTAP 9.10.1 以前である場合。
* ソース ボリュームのシステムがONTAPの任意のバージョンであり、キャッシュ ボリュームがONTAP 9.10.1 以前である場合。


回避策: キャッシュ ボリュームのルールを手動で作成する必要があります。



== 同じ名前のストレージVMのキャッシュ作成が失敗する

ソース クラスターと宛先クラスターが同じ名前のストレージ VM を使用する場合、キャッシュは作成されません。

回避策: ソース ストレージ VM とターゲット ストレージ VM に異なる名前を使用します。



== 新しいエクスポート ポリシーまたは最近編集されたエクスポート ポリシーの表示が遅れる

キャッシュを作成するときに、最近作成または編集されたエクスポート ポリシーがリストに表示されない場合があります。

回避策: 数分後に再試行してください。



== 宛先でCIFSプロトコルのみが有効になっている場合、キャッシュの作成は失敗します

ソース クラスタまたは宛先クラスタにONTAP 9.10.1 以前があり、宛先クラスタで CIFS プロトコルのみが有効になっている場合、キャッシュの作成は失敗します。

回避策: ONTAP 9.11.1 以降を実行しているか、CIFS プロトコルと NFS プロトコルの両方が設定されている宛先クラスタを使用します。
